export const INDUSTRIES = [
  { value: 'technology', label: 'Technology' },
  { value: 'retail', label: 'Retail' },
  { value: 'ecommerce', label: 'E-commerce' },
  { value: 'healthcare', label: 'Healthcare' },
  { value: 'finance', label: 'Finance' },
  { value: 'education', label: 'Education' },
  { value: 'manufacturing', label: 'Manufacturing' },
  { value: 'realestate', label: 'Real Estate' },
  { value: 'hospitality', label: 'Hospitality' },
  { value: 'professional', label: 'Professional Services' },
  { value: 'marketing', label: 'Marketing & Advertising' },
  { value: 'media', label: 'Media & Entertainment' },
  { value: 'logistics', label: 'Logistics & Supply Chain' },
  { value: 'construction', label: 'Construction' },
  { value: 'energy', label: 'Energy & Utilities' },
  { value: 'agriculture', label: 'Agriculture' },
  { value: 'nonprofit', label: 'Non-Profit' },
  { value: 'automotive', label: 'Automotive' },
  { value: 'aerospace', label: 'Aerospace & Defense' },
  { value: 'biotech', label: 'Biotechnology' },
  { value: 'telecom', label: 'Telecommunications' },
  { value: 'travel', label: 'Travel & Tourism' },
  { value: 'food', label: 'Food & Beverage' },
  { value: 'apparel', label: 'Apparel & Fashion' },
  { value: 'legal', label: 'Legal Services' },
  { value: 'consulting', label: 'Management Consulting' },
  { value: 'fitness', label: 'Fitness & Wellness' },
  { value: 'gaming', label: 'Gaming & Esports' },
  { value: 'other', label: 'Other' },
];

export const COMPANY_SIZES = [
  { value: '1-10', label: '1-10 Employees' },
  { value: '11-50', label: '11-50 Employees' },
  { value: '51-200', label: '51-200 Employees' },
  { value: '201-500', label: '201-500 Employees' },
  { value: '501-1000', label: '501-1000 Employees' },
  { value: '1000+', label: '1000+ Employees' },
];
